spring: 
  profiles: 
    active: 
      - dev
      
---
spring:
  profiles: dev #开发环境
  application: 
    name: cloud-config-dev
    
---
spring:
  profiles: test #测试环境
  application: 
    name: cloud-config-test
    
#注意保持UTF-8的格式，不然可能中文乱码